### ISSUE TITLE
Building the pattern library breaks the dashboard build

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#885]
Building the pattern library breaks the dashboard build.

Looks like it deletes some necessary files (these can be reinstated with an `npm run build` in `cg-style` — fixing the bug)

```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'cloudgov-style/css/base.css' in /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/static_src
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
resolve module cloudgov-style/css/base.css in /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/static_src
  looking for modules in /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules
    resolve 'file' or 'directory' css/base.css in /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style
      resolve file
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css.webpack.js doesn't exist
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css doesn't exist
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css.web.js doesn't exist
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css.js doesn't exist
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css.json doesn't exist
      resolve directory
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css doesn't exist (directory default file)
        /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/node_modules/cloudgov-style/css/base.css/package.json doesn't exist (directory description file)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/————/.nvm/versions/node/v6.7.0/bin/node" "/Users/————/.nvm/versions/node/v6.7.0/bin/npm" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! cloudgov-dashboard@1.12.0 build: `npm run clean && npm run check-style && node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloudgov-dashboard@1.12.0 build script 'npm run clean && npm run check-style && node_modules/webpack/bin/webpack.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cloudgov-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run check-style && node_modules/webpack/bin/webpack.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cloudgov-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cloudgov-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/————/code/18f/go/src/github.com/18F/cg-dashboard/npm-debug.log
```

**Comment by adborden** [comment]
You can work-around this by re-building `cg-style` once, and switching back to cg-dashboard.

    ~/cg-style $ npm run build
